-- MySQL Script generated by MySQL Workbench
-- Sat Oct 24 09:17:08 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema movies_db2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema movies_db2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `movies_db2` DEFAULT CHARACTER SET utf8 ;
USE `movies_db2` ;

-- -----------------------------------------------------
-- Table `movies_db2`.`genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db2`.`genres` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `name` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `ranking` INT(10) UNSIGNED NOT NULL,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `genres_ranking_unique` (`ranking` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `movies_db2`.`movies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db2`.`movies` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `title` VARCHAR(500) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `rating` DECIMAL(3,1) UNSIGNED NOT NULL,
  `awards` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `release_date` DATETIME NOT NULL,
  `length` INT(10) UNSIGNED NULL DEFAULT NULL,
  `genre_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `movies_genre_id_foreign` (`genre_id` ASC),
  CONSTRAINT `movies_genre_id_foreign`
    FOREIGN KEY (`genre_id`)
    REFERENCES `movies_db2`.`genres` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 50
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `movies_db2`.`actors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db2`.`actors` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `first_name` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `last_name` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `rating` DECIMAL(3,1) NULL DEFAULT NULL,
  `favorite_movie_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `country` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `actors_favorite_movie_id_foreign` (`favorite_movie_id` ASC),
  CONSTRAINT `actors_favorite_movie_id_foreign`
    FOREIGN KEY (`favorite_movie_id`)
    REFERENCES `movies_db2`.`movies` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 50
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `movies_db2`.`series`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db2`.`series` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `title` VARCHAR(500) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `release_date` DATETIME NOT NULL,
  `end_date` DATETIME NOT NULL,
  `genre_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `series_genre_id_foreign` (`genre_id` ASC),
  CONSTRAINT `series_genre_id_foreign`
    FOREIGN KEY (`genre_id`)
    REFERENCES `movies_db2`.`genres` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `movies_db2`.`seasons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db2`.`seasons` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `title` VARCHAR(500) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `number` INT(10) UNSIGNED NULL DEFAULT NULL,
  `release_date` DATETIME NOT NULL,
  `end_date` DATETIME NOT NULL,
  `serie_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `seasons_serie_id_foreign` (`serie_id` ASC),
  CONSTRAINT `seasons_serie_id_foreign`
    FOREIGN KEY (`serie_id`)
    REFERENCES `movies_db2`.`series` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 47
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `movies_db2`.`episodes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db2`.`episodes` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `title` VARCHAR(500) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `number` INT(10) UNSIGNED NULL DEFAULT NULL,
  `release_date` DATETIME NOT NULL,
  `rating` DECIMAL(3,1) NOT NULL,
  `season_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `episodes_season_id_foreign` (`season_id` ASC),
  CONSTRAINT `episodes_season_id_foreign`
    FOREIGN KEY (`season_id`)
    REFERENCES `movies_db2`.`seasons` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 58
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `movies_db2`.`actor_episode`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db2`.`actor_episode` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `actor_id` INT(10) UNSIGNED NOT NULL,
  `episode_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `actor_episode_actor_id_foreign` (`actor_id` ASC),
  INDEX `actor_episode_episode_id_foreign` (`episode_id` ASC),
  CONSTRAINT `actor_episode_actor_id_foreign`
    FOREIGN KEY (`actor_id`)
    REFERENCES `movies_db2`.`actors` (`id`),
  CONSTRAINT `actor_episode_episode_id_foreign`
    FOREIGN KEY (`episode_id`)
    REFERENCES `movies_db2`.`episodes` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 149
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `movies_db2`.`actor_movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db2`.`actor_movie` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `actor_id` INT(10) UNSIGNED NOT NULL,
  `movie_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `actor_movie_actor_id_foreign` (`actor_id` ASC),
  INDEX `actor_movie_movie_id_foreign` (`movie_id` ASC),
  CONSTRAINT `actor_movie_actor_id_foreign`
    FOREIGN KEY (`actor_id`)
    REFERENCES `movies_db2`.`actors` (`id`),
  CONSTRAINT `actor_movie_movie_id_foreign`
    FOREIGN KEY (`movie_id`)
    REFERENCES `movies_db2`.`movies` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 59
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `movies_db2`.`migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db2`.`migrations` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `migration` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `batch` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `movies_db2`.`password_resets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db2`.`password_resets` (
  `email` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `token` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  INDEX `password_resets_email_index` (`email` ASC),
  INDEX `password_resets_token_index` (`token` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `movies_db2`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db2`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
